export const APP_LIMITS = {
  usernameMaxLength: 32,
  sellerDisplayNameMaxLength: 60,
  productNameMaxLength: 80,
  productDescriptionMaxLength: 600,
  productImagesMaxCount: 4,
  productImageMaxSizeMb: 2,
  searchInputMaxLength: 4000,
  bulkLoadMaxItems: 2500,
  passwordMinLength: 8,
};

export const SEARCH_FILTERS = {
  kinds: ["todas", "comun", "fluor", "holo"],
  variants: [
    "todas",
    "base",
    "azul",
    "verde",
    "rojo",
    "amarillo",
    "plateado",
    "dorado",
    "dorado opaco",
    "plateado opaco",
    "glitter",
    "fluor",
    "fantasma",
  ],
  expansions: [
    "todas",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "Personajes",
    "7",
    "Guerreros 1",
    "Guerreros 2",
    "Super Batalla 1",
    "Super Batalla 2",
    "GT",
    "Batalla Final 1",
    "Batalla Final 2",
  ],
};
