export const APP_LIMITS = {
  usernameMaxLength: 32,
  sellerDisplayNameMaxLength: 60,
  productNameMaxLength: 80,
  productDescriptionMaxLength: 600,
  productImagesMaxCount: 1,
  productImageMaxSizeMb: 1,
  searchInputMaxLength: 4000,
  bulkLoadMaxItems: 2500,
  passwordMinLength: 8,
};

export const SEARCH_FILTERS = {
  kinds: ["todas", "comun", "fluor", "holo"],
  variants: [
    "todas",
    "Base",
    "arcoiris",
    "azul",
    "bronce",
    "celeste",
    "dorado",
    "dorado opaco",
    "fluor",
    "naranja",
    "patrones",
    "plateado",
    "plateado opaco",
    "rosa",
    "rojo",
    "tornasolado",
    "turquesa",
    "verde",
    "violeta",
    "amarillo",
    "glitter",
    "fantasma",
  ],
  expansions: [
    "todas",
    "Expansión 1",
    "Expansión 2",
    "Expansión 3",
    "Cartas ocultas",
    "Expansión 4",
    "Expansión 5",
    "Expansión 6",
    "Personajes",
    "Expansión 7",
    "Guerreros Legendarios 1",
    "Guerreros Legendarios 2",
    "Super Batalla 1",
    "Super Batalla 2",
    "GT",
    "Batalla Final 1",
    "Batalla Final 2",
  ],
};
